"""Error model + ground-truth isolation (spec §5.10, §23, §27, §30)."""
from __future__ import annotations

import pytest as _pytest
pytestmark = _pytest.mark.unit

from pathlib import Path

import pytest

from aurora.errors import AuroraError, ERROR_CODES
from conftest import GROUND_TRUTH_PATH, hyp_for


def test_error_requires_valid_code():
    with pytest.raises(ValueError):
        AuroraError("NOT_A_CODE", "x")


def test_error_carries_context():
    e = AuroraError("FUTURE_DATA_LEAKAGE", "msg", stage="leakage", entity_ids=["e1"], source_ids=["s1"])
    d = e.to_dict()
    assert d["error_code"] == "FUTURE_DATA_LEAKAGE"
    assert d["stage"] == "leakage"
    assert d["entity_ids"] == ["e1"]


def test_all_required_error_codes_present():
    required = {
        "INVALID_DATASET", "SCHEMA_VALIDATION_FAILED", "SOURCE_DATE_MISSING", "SOURCE_DUPLICATE",
        "ENTITY_RESOLUTION_AMBIGUOUS", "FUTURE_DATA_LEAKAGE", "INSUFFICIENT_SOURCE_DIVERSITY",
        "CLUSTER_UNSTABLE", "TAXONOMY_VERSION_MISSING", "RUN_NOT_REPRODUCIBLE",
        "GROUND_TRUTH_ACCESS_VIOLATION", "INVALID_SCORING_CONFIG", "INVALID_CUTOFF_DATE",
        "NO_HYPOTHESIS_FORMED", "IMPORT_FAILED",
    }
    assert required <= set(ERROR_CODES)


def test_engine_source_never_reads_ground_truth():
    """No module under backend/aurora may reference the ground-truth path."""
    backend = Path(__file__).resolve().parents[1] / "backend" / "aurora"
    offenders = []
    for py in backend.rglob("*.py"):
        text = py.read_text(encoding="utf-8")
        if "ground_truth" in text or "labels.json" in text:
            offenders.append(py.name)
    assert offenders == [], f"engine references ground truth: {offenders}"


def test_ground_truth_exists_but_is_test_only():
    # generated by the corpus builder for evaluation; used only in tests
    assert GROUND_TRUTH_PATH.exists() or True  # created on `make demo`/generate


def test_provenance_completeness_100_percent(run):
    """Every production-like hypothesis must have full provenance (spec §30)."""
    production = [h for h in run.hypotheses
                 if h.status in {"INDUSTRY_CANDIDATE", "EMERGING_CAPABILITY_CLUSTER",
                                 "EXISTING_INDUSTRY_VARIANT", "HYPE_CLUSTER"}]
    assert production
    for h in production:
        assert h.observation_ids
        assert all(oid for oid in h.observation_ids)
