"""initial schema: snapshots, entities, sources, observations, runs

Revision ID: ec328ff867b1
Revises: 
Create Date: 2026-07-23 22:17:02.795409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec328ff867b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('cutoff_date', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('result_manifest_hash', sa.String(), nullable=False),
    sa.Column('input_manifest_hash', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_research_runs_snapshot_id'), 'research_runs', ['snapshot_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('resolved_group', sa.JSON(), nullable=False),
    sa.Column('import_errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'snapshot_id')
    )
    op.create_table('observations',
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('subject_entity', sa.String(), nullable=False),
    sa.Column('observation_type', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('observation_id', 'snapshot_id')
    )
    op.create_index(op.f('ix_observations_observation_type'), 'observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_observations_subject_entity'), 'observations', ['subject_entity'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_index(op.f('ix_observations_subject_entity'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_type'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('entities')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_research_runs_snapshot_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
